[Step3 - Event] 김현태 미션 제출합니다.
next-step/jpa-bootstrap pull request #37
Opened 2024-03-20 14:39 UTC by Hyunta

안녕하세요 종민님,
Event, ActionQueue 구현해야하는 내용이 너무 많네요...ㅠㅠ
쭈욱 만들다가 중간에 Intellij 에러인지 갑자기 저장이 안된 상태로 꺼져버렸네요... 이런적이 처음인데 이번에 2번정도 그랬네요;;
기억에 의존해서 다시 만들다보니 중간에 누락된 부분이 있을수도 있을 것 같습니다.

지금 테스트가 하나 깨지는데 ( Save할 때 Id 받아오는 로직을 actionQueue로 넘기면서 꼬인 것 같습니다...)
아직 마음에 들지 않는 부분들이 많은데 일정이 여유롭지가 못해서 우선 리뷰요청 드리고,
계속 개선해보도록 하겠습니다!

2024-03-20 16:42 UTC, jongmin4943 requested changes
안녕하세요 현태님!

3단계 미션도 잘 진행해주셨네요 👍 
테스트가 깨지는 부분에 대한 코멘트와, 질문에 대한 답변을 달아 보았습니다 😄
그 외에 소소한 코멘트들 남겨놓았으니 확인 후 재요청 부탁드릴게요 🙏

미션 진행하시며 궁금한 사항이 있으시면 편하게 코멘트 또는 DM 주세요! 😃

2024-03-20 16:42 UTC, jongmin4943 commented on src/main/java/boot/EntityManagerContext.java
> +}
피드백 반영해주셨네요 👍

2024-03-20 16:42 UTC, jongmin4943 commented on src/main/java/boot/MyEntityManagerContext.java
> +    }
remove 메서드를 만들어 주셨네요 💯
사용되는 부분이 나올때 활용해주면 좋을 것 같아요 😃

2024-03-20 16:42 UTC, jongmin4943 commented on src/main/java/boot/action/ActionQueue.java
> +    }
깔끔하게 Action 의 실행순서를 정해놓으셨네요 💯

다만 한가지 고민해볼 포인트가 있어요 🤔
같은 Entity 에 대해 InsertAction 이 여러번 쌓이면 어떻게 처리해야 할까요?
같은 의미로 UpdateAction 이 여러번 쌓일 경우 마지막으로 update 된 상태의 Entity 를 기준으로 한번의 update 쿼리만 나가야 하지 않을까요?  :)

2024-03-20 16:42 UTC, jongmin4943 commented on src/main/java/boot/action/EntityInsertAction.java
> +    }
`EntityInsertAction` 은 다른 `EntityUpdateAction`, `EntityDeleteAction` 들과 다르게 왜 `EntityMeta` 가 필요한지 고민해 보았어요 👀 

아마 insert 이후 id 주입을 위해 사용되는 부분때문에 그런게 아닐까 싶은데, entityPersister 에 이미 id 주입을 위한 필요한 정보들이 있는것 처럼 보여요.
`entityPersister.insert` 메서드에서 id 를 주입하는 책임도 가지게 된다면 구조가 좀 더 간단해질 것 같은데 어떻게 생각하시나요? 😃

2024-03-20 16:42 UTC, jongmin4943 commented on src/main/java/boot/action/ActionQueue.java
> +    }
> 지금 테스트가 하나 깨지는데 로직 개선하면서 수정하겠습니다( Save할 때 Id 받아오는 로직을 actionQueue로 넘기면서 꼬인 것 같습니다...)

현재 테스트가 깨지는건 insert 가 flush 메서드 실행 전까지 실제로 실행되지 않다보니 id 가 없어서 생기는 문제같아요 🤔
JPA 는 id 채번 방식에 따라 전략이 나뉘는데, auto_increment 라면 insert 를 쌓지 않고 바로 실행시켜 entity 에 id 를 바인딩 시켜주는 전략을 가지고 있는데요. 해당 전략에 따른 분기부분은 현재 요구사항에는 없기 때문에 만들기에 너무 과하다 생각하시면, insert 정도만 바로바로 실행시켜주시는 방식으로 해결 해 주셔도 됩니다 😄
```suggestion
    public void addAction(EntityInsertAction<?> action) {
        insertions.add(action);
        executeAllInsertions();
    }
```

해당 코드로 바꾼 뒤 테스트를 돌려보면 한군데가 깨지는데, 해당 테스트는 한번 로직을 체크해보실 필요가 있을 것 같아요 :) 밑에 코멘트 달아 놓았습니다!

2024-03-20 16:42 UTC, jongmin4943 commented on src/main/java/event/EventListenerGroup.java
> +    }
`EventListenerGroup` 을 잘 만들어주셨네요 💯

2024-03-20 16:42 UTC, jongmin4943 commented on src/main/java/event/EventListenerGroup.java
> +    }
> Casting이 아니라 EventType의 eventListener 타입을 잘 조합하면 사용할 수 있을 것 같은데 도와주세요.

해당 부분은 저도 저번 기수 미션 진행할때 고민했던 부분이랍니다 😃 
Hibernate 처럼 선언하는게 아닌, Enum 으로 빼게 될 경우 제네릭 정보가 제대로 활용되지 못해서 생기는 이슈인데요 👀

제 개인적인 견해로는 해당 부분에 두가지 정도 대안이 있어요. 만약 다른 방안을 알게 되시면 공유 부탁드려요 ㅎㅎ

1. 제네릭을 활용할 수 있게끔 eventListeners 의 value 부분의 EventListener를 한번 더 객체로 감싸는거에요. `new EventListenerWrapper<>(new DefaultLoadEventListener(metaModel))` 이런 느낌으로요 ㅎㅎ
그리고 나서  `EventListenerWrapper` 클래스는 event 와 BiConsumer나 BiFunction 을 이용해 내부 eventListener 를 실행할 수 있는 구조로 만드시는거죠! 사용하실땐 EventListenerWrapper.실행(event객체, eventListener::on이벤트); 이런느낌으로 사용이 가능하게요 😄 글로 만 설명으로는 이해하기 어려워보이니 제 개인적 코드를 첨부해드릴게요. 참고만 부탁드려요!
```java
// EventListenerGroup.java
public class EventListenerGroup {

    private final Map<EventType, EventListenerWrapper<?>> eventListeners;

    private EventListenerGroup(Map<EventType, EventListenerWrapper<?>> eventListeners) {
        this.eventListeners = eventListeners;
    }

    public static EventListenerGroup createDefaultGroup(MetaModel metaModel, ActionQueue actionQueue) {
        Map<EventType, EventListenerWrapper<?>> eventListeners = new ConcurrentHashMap<>();
        eventListeners.put(EventType.LOAD, new EventListenerWrapper<>(new DefaultLoadEventListener(metaModel)));
        eventListeners.put(EventType.SAVE, new EventListenerWrapper<>(new DefaultSaveEventListener(metaModel, actionQueue)));
        eventListeners.put(EventType.UPDATE, new EventListenerWrapper<>(new DefaultUpdateEventListener(metaModel, actionQueue)));
        eventListeners.put(EventType.DELETE, new EventListenerWrapper<>(new DefaultDeleteEventListener(metaModel, actionQueue)));
        return new EventListenerGroup(eventListeners);
    }

    @SuppressWarnings("unchecked")
    public <T> EventListenerWrapper<T> getListener(EventType eventType) {
        if (!eventListeners.containsKey(eventType)) {
            throw new IllegalArgumentException("EventListener does not exist for the type : " + eventType);
        }
        return (EventListenerWrapper<T>) eventListeners.get(eventType);
    }
}

// EventListenerWrapper.java
public class EventListenerWrapper<EVENT_LISTENER>  {
    private final EVENT_LISTENER eventListener;

    public EventListenerWrapper(EVENT_LISTENER eventListener) {
        this.eventListener = eventListener;
    }

    public <EVENT, RETURN> RETURN fireEventReturn(EVENT event, BiFunction<EVENT_LISTENER, EVENT, RETURN> action) {
        return action.apply(eventListener, event);
    }

    public <EVENT> void fireEvent(EVENT event, BiConsumer<EVENT_LISTENER, EVENT> action) {
        action.accept(eventListener, event);
    }
}

// MyEntityManager.java
// find 메서드 중 일부
EventListenerWrapper<LoadEventListener> listener = eventListenerGroup.getListener(EventType.LOAD);
T foundEntity = listener.fireEventReturn(new LoadEvent<>(clazz, id), LoadEventListener::onLoad);
```

2. 두번째 방법은 좀 더 깔끔한 방법이라 생각하는 Dispatcher 를 만들어서 처리하는 방식이에요. 단순히 EventListener를 반환하는 방식이 아닌, Dispatcher가 받아서 처리까지 해버리는 거죠. 그럴려면 Event 들을 한단계 더 추상화 해야하는데요! 해당 방식도 궁금하시다면 도전해보시는걸 과제로 남겨드려보겠습니다 ㅎㅎ

참고로 Hibernate 는 1번의 방식과 유사한 방식으로 작동하고 있다는점 참고 부탁드려요! 😃

2024-03-20 16:42 UTC, jongmin4943 commented on src/main/java/persistence/persistencecontext/PersistenceContext.java
> +    Object getCachedDatabaseSnapshot(Object id, Object entity);
피드백 반영해주셨네요 👍 고민해주시고 의견 나눠주셔서 감사해요 😃

2024-03-20 16:42 UTC, jongmin4943 commented on src/test/java/persistence/entity/MyEntityManagerTest.java
>          entityManager.persist(expected);
아마 insert 관련 피드백이 반영되면 해당 테스트가 깨지게 될 거에요 👀
해당 테스트 시나리오가 살짝 문제가 있다고 생각이 되는데요!
given 에서 persist, when 에서 remove, 그리고 then 에서 find 시 `RuntimeException` 이 던져지는걸 검증하셨는데, find 시 `PersistenceContext` 에 값이 없으면 loader 가 작동하다보니, Exception 이 날 수 없는 구조 같아요 🤔

2024-03-21 04:10 UTC, Hyunta commented on src/main/java/boot/action/EntityInsertAction.java
> +    }
그러게요...기존 구조를 그대로 옮기면서 고민을 못해봤던 부분인 것 같습니다.
entityPersister에서 insert할 때 id까지 주입해주도록 수정해서 구조 개선하도록 하겠습니다!

2024-03-21 04:37 UTC, Hyunta commented on src/main/java/boot/MyEntityManagerContext.java
> +    }
사용하려고 시도해봤는데 잘 떠오르지가 않네요.
1. ThreadLocal에 저장해놓고, EntityManager가 flush할 때 불러와서 close 하는 방법
2. EntityManager를 생성할 때 Context를 같이 전달해주는 방법
그리고 entityManager가 flush 됐을 때가 올바른 시점인지? transaction이 commit 될 때 remove 트리거가 작동하면 되지 않을까 싶습니다.

2024-03-21 10:27 UTC, Hyunta commented on src/main/java/boot/action/ActionQueue.java
> +    }
우선 제안주신대로 변경한 뒤 문제가 발생하는 부분을 수정해보도록 하겠습니다!

2024-03-21 10:46 UTC, Hyunta commented on src/test/java/persistence/entity/MyEntityManagerTest.java
>          entityManager.persist(expected);
피드백 반영 이후 대책까지 함께해주셔서 너무 감사합니다 종민님 😁
JdbcTemplate에 의존하는 부분이긴한데, 조회해올 때 만약에 값이 없으면 RuntimeException을 던지도록 한 부분을 이용해서 테스트를 했었습니다!
제가 파악해봤을 때 해당 테스트가 깨졌던 이유가 delete도 마찬가지로 flush가 일어나야 반영되서 그랬던 것 같습니다. 그런데 제가 snapShot을 삭제해주지 않았더라구요, 그 부분도 수정했습니다.

만약에 제가 커멘트 의도를 잘못 파악했다면 다시 공유해주세요

2024-03-21 11:56 UTC, Hyunta commented on src/main/java/event/EventListenerGroup.java
> +    }
힌트 감사합니다 종민님!
제네릭으로 구조를 잡는게 익숙치 않아서 T,U,V 이런식으로 써놓으면 헷갈렸었는데,
명확하게 들어오는 타입에 대해서는 EVENT_LISTENER 이런식으로 지정해주는 것도 좋은 방법인 것 같습니다!
이 부분은 제 코드에 반영해보고 싶어서 적용해봤습니다ㅎㅎ

우선 1번을 참고해서 코드에 반영해봤습니다!
2번 Dispatcher 방식으로 구현한다고 생각해서 상상코딩을 해봤는데요ㅎㅎ
EntityManager가 EventListenerGroup 대신 EventDispatcher를 들고 Event를 전달해주고,
EventDispatcher에서 Listener를 조회해서 해당하는 메서드들 수행하는 방식으로 구현할 수 있을 것 같습니다!

EventType에 있는 eventName, eventListenerClass는 사용하지 않았는데 혹시 이게 어떤식으로 사용되는지? 왜 필요한지 궁금합니다.

2024-03-21 11:57 UTC, Hyunta commented
안녕하세요 종민님,
항상 리뷰를 빠르고, 꼼꼼하게 봐주셔서 너무 감사합니다!
Event 미션 정말 복잡했었는데 피드백 반영하면서 진행하니 윤곽이 편하게 잡히는 것 같습니다ㅎㅎ
남겨주신 피드백에 대한 생각과 주신 커멘트 반영해봤습니다!

2024-03-21 13:17 UTC, jongmin4943 requested changes
안녕하세요 현태님 😃

피드백 반영 잘 해주셨네요 💯 
한가지 피드백에 대한 답변이 없는데 해당 부분과 몇몇 사소한 코멘트 부분만 확인해주시면 마무리 단계가 될 것 같아요 👍 
혹시 추가적인 궁금점이나 도전해보고 싶은게 있으시다면 merge 전에 DM 또는 코멘트를 통해서 말씀해주세요! 마무리되셨다고 생각하시고 말씀해주시면 merge 하겠습니다🙇

2024-03-21 13:17 UTC, jongmin4943 commented on src/main/java/boot/MyEntityManagerContext.java
> +    }
일반적으로 트랜잭션 범위 내에서 관리되긴하지만, 현재와 같이 트랜잭션이 없을땐 명시적으로 특정 부분에서 제거가 되면 좋을 것 같아요. Thread 를 key 로 잡아주셨으니, 해당 Thread 에서 EntityManager 와 관련된 작업이 종료되는 시점이면 좋겠다 라고 생각했어요 :)

[Jpa spec](https://download.oracle.com/otn-pub/jcp/persistence-2_2-mrel-spec/JavaPersistence.pdf?AuthParam=1709981917_9aadd9137c2b0417cd0c1d7bbef5afe9#page=65&zoom=100,94,136) 에는 close 라는 메서드를 제공하고 있어요! 스펙과 조금 다르긴 하지만, 개인적으로 현재 상황에서는 해당 메서드를 활용해보는것도 괜찮아 보여요😃

2024-03-21 13:17 UTC, jongmin4943 commented on src/main/java/event/EventListener.java
> +}
현재 해당 interface가 정말 필요할까요?

2024-03-21 13:17 UTC, jongmin4943 commented on src/main/java/event/EventListenerGroup.java
> +    }
Wrapper 를 통해 한번 감싸는 방식을 이용해주셨네요 👍 
사소하지만, 현재 자료구조를 `ConcurrentHashMap` 을 사용하셨는데 딱히 이점이 없다 생각이 들어요 🤔
현태님은 어떤 기준으로 `ConcurrentHashMap`을 사용해주셨나요?

2024-03-21 13:17 UTC, jongmin4943 commented on src/main/java/event/EventType.java
> +    }
> EventType에 있는 eventName, eventListenerClass는 사용하지 않았는데 혹시 이게 어떤식으로 사용되는지? 왜 필요한지 궁금합니다.

Hibernate 의 `EventType` 클래스가 eventName 을 String 으로 받는 이유는 유연성을 제공하기 때문이라 생각해요. eventListenerClass 필드를 사용하는것도 비슷한 결이라 느끼고요 ㅎㅎ

Hibernate 의 [EventEngine](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/event/spi/EventEngine.java#L32) 이라는 클래스를 보시면 아마 저와 비슷한 느낌을 느끼시지 않을까 싶어요! 

Enum 은 강력한 안정성을 제공하지만, 유연성이 떨어지는 문제가 있어요. 라이브러리라는 점에서, Enum 대신 String 을 활용함으로써 유연함을 제공한다 생각해요 😃

2024-03-21 13:17 UTC, jongmin4943 commented on src/main/java/persistence/entity/MyEntityPersister.java
>      }
피드백 반영 해주셨네요 💯

2024-03-21 13:17 UTC, jongmin4943 commented on src/test/java/persistence/entity/MyEntityManagerTest.java
>          entityManager.persist(expected);
아하, 그렇네요. 제가 잘못 파악한 것 같네요. 말씀하신대로, flush 가 안되어서 delete 가 안되었고 해당 부분이 문제가 되었네요 😃

제가 착각하게 된 것은, 실제 JPA 에서는 flush 가 일어나지 않아도 persist -> remove -> find 순으로 진행 시 Exception 이 아니라 null 을 반환한다는 점과 헷갈린것 같습니다. `JdbcTemplate.queryForObject` 에서 이미 Exception 을 던지고 있었네요 😅

2024-03-21 13:17 UTC, jongmin4943 commented on src/main/java/boot/action/ActionQueue.java
> +    }
해당 피드백에 대한 답변을 못받은 것 같은데 확인 하셨을까요? 👀

2024-03-22 10:44 UTC, Hyunta commented on src/main/java/boot/action/ActionQueue.java
> +    }
제가 읽었는데 누락한 것 같습니다. 재확인 해주셔서 감사합니다.
ActionQueue라고 해서 크게 고민 없이 Queue를 사용했었는데 Set을 사용하는게 더 적절할 것 같아서 수정했습니다.
추가로 Event의 객체끼리 동등성 비교가 필요할 것 같아서 equals와 hashcode를 재정의했습니다.

2024-03-22 10:47 UTC, Hyunta commented on src/main/java/event/EventListener.java
> +}
Wrapper로 수정하게 되면서 더이상 불필요할 것 같습니다!
삭제하도록 하겠습니다

2024-03-22 10:51 UTC, Hyunta commented on src/main/java/event/EventListenerGroup.java
> +    }
처음에 설계했었을 때는 listener가 계속 추가되고 변경될 수 있겠다 싶어서 안전하게 ConcurrentHashMap을 사용했습니다.
현재 구조에서는 가져갈 이점이 없지만, 추후에 Listener를 추가하는 기능이 생겼을 때 안전하게 대응할 수 있을 것 같습니다!

2024-03-22 10:53 UTC, Hyunta commented on src/main/java/event/EventType.java
> +    }
아 뭔가 중간에서 처리해주는 객체가 따로 있군요!
Hibernate 클래스까지 공유해주셔서 감사합니다ㅎㅎ
대략적으로 큰 그림은 얼추 그려지는 것 같네요😁

2024-03-22 10:55 UTC, Hyunta commented
안녕하세요 종민님,
실수로 저번에 피드백 하나를 누락했었네요..ㅠㅠ
이번에는 남겨주신 피드백까지 더블체크 했습니다!
혹시 또 누락됐거나, 반영한 부분에서 피드백이 있으면 알려주세요ㅎㅎ
마무리 해도 괜찮을 것 같습니다
마지막 단계 종민님 덕분에 알차게 진행할 수 있었습니다.
좋은 인사이트를 많이 공유해주셔서 너무 감사해요 🙇🏻‍♂️

2024-03-22 14:14 UTC, jongmin4943 approved these changes
안녕하세요 현태님 😃

피드백에 대해 고민해주시고 반영해 해주셔서 감사합니다 🙇
현태님과 미션 진행하며 많은 인사이트를 얻을 수 있었습니다.
저와 함께한 미션 시간이 좋은 기억으로 기억되길 바라겠습니다!

그동안 바쁜 와중에도 성실히 미션 수행하시느라 고생 많으셨습니다! 🚀

2024-03-22 14:14 UTC, merged