2단계 - SessionFactory
next-step/jpa-bootstrap pull request #65
Opened 2024-11-11 16:42 UTC by jsyang-dev

종민님, 안녕하세요! 
2단계 리뷰 요청드립니다.

이번 단계는 빨리 끝났는데, 빠뜨린 요구 사항이 있나 걱정되네요.
그럼 이번 리뷰도 잘 부탁드립니다! 🙇‍♂️🙇‍♂️🙇‍♂️

2024-11-12 11:49 UTC, jongmin4943 requested changes
안녕하세요 정수님!

2단계 미션 깔끔하게 잘해주셨네요 💯 
만들어주신 부분에서 고민 할 만한 코멘트 몇 가지 달아보았습니다. 확인 후 재 요청 주세요 🙇

미션 진행하시며 궁금한 사항이 있으시면 편하게 코멘트 또는 DM 주세요! 🔥

2024-11-12 11:49 UTC, jongmin4943 commented on src/main/java/persistence/bootstrap/ComponentScanner.java
> +    private final EntityBinder entityBinder;
`ComponentScanner` 가 `EntityBinder` 를 가지는 형태가 되었네요.
제가 드렸던 피드백의 방향은 `ComponentScanner` 는 Entity 라는 것과 연관관계가 완전 끊어지고, `EntityBinder` 가 `ComponentScanner` 를 사용하는 방향이었어요. ㅎㅎ

반영을 위한 피드백은 아니니 참고만 부탁드려요 👍

2024-11-12 11:49 UTC, jongmin4943 commented on src/main/java/persistence/entity/DefaultEntityManager.java
>      }
깔끔해졌네요 💯

2024-11-12 11:49 UTC, jongmin4943 commented on src/main/java/persistence/entity/PersistenceContext.java
> -import persistence.meta.EntityTable;
`PersistenceContext` 에서 `EntityTable` 과의 연관관계를 잘 끊어주셨네요.
개인적으로 `EntityKey` 도 패키지를 옮겨서 `persistence.meta` 과의 의존성도 없애보면 좋을 것 같아요 :)

2024-11-12 11:49 UTC, jongmin4943 commented on src/main/java/persistence/meta/EntityColumn.java
>          } catch (IllegalAccessException e) {
메서드 이름이 좀 더 명확해졌네요 👍 
하나 신경쓰이는건, field 의 accessible 문제로 null 이 반환되는 상황인데 괜찮을까요?

2024-11-12 11:49 UTC, jongmin4943 commented on src/test/java/persistence/entity/EntityManagerFactoryTest.java
> +    }
해당 테스트는 `DisplayName` 은 동일성 체크로 되어있지만 실제로는 동등성 비교를 하고 있는데 의도하신걸까요?

2024-11-12 11:49 UTC, jongmin4943 commented on src/main/java/persistence/entity/manager/CurrentSessionContext.java
> +    }
동일한 Thread 에서 서로 다른 `EntityManager` 들이 만들어지고, `openSession` 을 여러번 호출하게 되면 문제가 될 수 있을 것 같아요 🤔 어떻게 처리하는게 좋을까요?

2024-11-12 11:49 UTC, jongmin4943 commented on src/main/java/persistence/entity/manager/CurrentSessionContext.java
> +    }
`closeSession` 이 동작할 때 추가로 고려 해볼 만한 점이 뭐가 있을까요? 

<details>
<summary>힌트</summary>

`EntityManager` 의 영속성 컨텍스트에 있는 Entity 들은 어떻게 되어야 할까요?
</details>

2024-11-12 11:49 UTC, jongmin4943 commented on src/main/java/persistence/entity/manager/factory/EntityManagerFactory.java
> +public class EntityManagerFactory {
`EntityManagerFactory` 를 잘 만들어주셨네요 💯 

만들어주신 `EntityManagerFactory` 를 이용해보려 하니 문제가 있네요. `entityManager.persist` 를 호출하니 table 정보가 존재하지 않는다네요. 😢 언제 table 들이 생성되어야 할까요?

2024-11-12 12:32 UTC, jsyang-dev commented on src/main/java/persistence/meta/EntityColumn.java
>          } catch (IllegalAccessException e) {
예외를 던지는게 맞을 것 같네요

2024-11-12 12:35 UTC, jsyang-dev commented on src/test/java/persistence/entity/EntityManagerFactoryTest.java
> +    }
의도한건 아닙니다 😅
 isSameAs 를 사용해야 되겠네요!

2024-11-12 12:54 UTC, jsyang-dev commented on src/main/java/persistence/entity/manager/CurrentSessionContext.java
> +    }
엔티티들의 정리가 필요하겠네요!

2024-11-12 16:26 UTC, jsyang-dev commented on src/main/java/persistence/entity/manager/factory/EntityManagerFactory.java
> +public class EntityManagerFactory {
Metamodel이 초기화되는 시점에 DB와 엔티티의 동기화가 필요할 것 같아요.
테이블이 존재하는지 여부에 따라 생성하거나 타입 체크 등을 해야할 것 같은데, 우선은 테이블 생성 로직만 추가하겠습니다.

2024-11-13 02:36 UTC, jongmin4943 approved these changes
안녕하세요 정수님!

2단계 빠르게 피드백 반영해주셨네요 💯 
몇 가지 사소한 부분에 제 의견을 코멘트로 달아보았어요 😃 다음 단계 진행하시며 참고 부탁드려요 🙇

여기서 2단계는 merge 하도록 하겠습니다. 마지막 3단계 Event 미션 진행하러 가보시죠 🚀

2024-11-13 02:36 UTC, jongmin4943 commented on src/main/java/persistence/bootstrap/DatabaseSyncManager.java
> +        final CreateQuery createQuery = new CreateQuery(new H2Dialect());
`DatabaseSyncManager` 를 만들어주셨네요 👍  

개인적으로 Dialect 의 구현체는 외부에서 결정되는게 어떨까 싶어요 :)

2024-11-13 02:36 UTC, jongmin4943 commented on src/main/java/persistence/bootstrap/Metamodel.java
> +        DatabaseSyncManager.sync(entityTableBinder, entityAssociationBinder, jdbcTemplate);
`Metamodel` 에서 `DatabaseSyncManager.sync` 와 `DatabaseSyncManager.cleaer` 를 사용해주셨네요 👍 

개인적으로 `Metamodel` 은 metadata 를 다루는 책임만 가지고, database 와의 동기화 실행의 책임은 다른 곳에 있으면 어떨까 고민이 드네요 :)

2024-11-13 02:36 UTC, jongmin4943 commented on src/main/java/persistence/bootstrap/binder/EntityAssociationBinder.java
> +    private final Map<String, EntityAssociation> entityAssociationRegistry = new HashMap<>();
`EntityAssociation` 을 따로 관리해주셨네요 💯

2024-11-13 02:36 UTC, jongmin4943 commented on src/main/java/persistence/bootstrap/binder/EntityAssociationBinder.java
> +            if (Objects.isNull(associationEntityColumn)) {
사소하지만 `Objects.isNull` 은 메서드참조와 같은 함수형 부분에서 주로 사용하고, 그 외에는 `== null` 과 같은 코드가 좀 더 읽기 편하더라구요 :)

2024-11-13 02:36 UTC, jongmin4943 commented on src/main/java/persistence/entity/manager/CurrentSessionContext.java
> +    public synchronized EntityManager openSession(EntityManager entityManager) {
`synchronized` 를 사용해주셨네요. `ThreadLocal` 을 사용하고 있는데 `synchronized` 가 필요한 때는 언제 일까요?

2024-11-13 02:36 UTC, jongmin4943 commented on src/main/java/persistence/entity/manager/CurrentSessionContext.java
> +        return entityManager;
외부에서 `EntityManager` 를 새로 생성해서 `openSession` 을 호출했는데, 반환되는건 새로 생성된 `EntityManager` 가 아닐 수 있다보니, 사용자의 의도와 다르게 작동 할 수 있을 것 같아요.

현재 구현 방향에서는 예외를 던지는 방향이 좀 더 낫지 않을까요?

2024-11-13 02:36 UTC, jongmin4943 commented on src/main/java/persistence/entity/manager/CurrentSessionContext.java
> +    }
피드백에 대해 고민해주셨네요 👍 
spec 상 close 시 각종 리소스를 회수하고, `EntityManager` 가 가진 대부분의 메서드 호출 시 에러가 나도록 처리 됩니다 :) 

![image](https://github.com/user-attachments/assets/4ecacdb6-eb4e-45a6-8790-fd2d9360d8ee)

2024-11-13 02:36 UTC, jongmin4943 commented on src/main/java/persistence/meta/EntityColumn.java
>          } catch (IllegalAccessException e) {
개인적으로 `accessible(true)` 로 바꿔서 예외가 안나도록 처리도 추가되면 좋을 것 같아요 :)

2024-11-13 02:36 UTC, merged

2024-11-13 11:37 UTC, jsyang-dev commented on src/main/java/persistence/bootstrap/binder/EntityAssociationBinder.java
> +            if (Objects.isNull(associationEntityColumn)) {
둘중에 어떤 것을 사용하는 것이 더 가독성이 좋을까 고민을 많이 했었는데, 명쾌한 답을 주셨네요!

2024-11-13 11:54 UTC, jsyang-dev commented on src/main/java/persistence/entity/manager/CurrentSessionContext.java
> +    public synchronized EntityManager openSession(EntityManager entityManager) {
`openSession`에서 동시에 `sessionRegistry.get()` 을 하는 것을 방지하기 위해서 `synchronized `를 적용해봤습니다

2024-11-13 16:25 UTC, jsyang-dev commented on src/main/java/persistence/bootstrap/Metamodel.java
> +        DatabaseSyncManager.sync(entityTableBinder, entityAssociationBinder, jdbcTemplate);
종민님은 동기화 실행의 책임을 어느 객체가 갖는 것이 좋다고 생각하시는지 궁금합니다!

2024-11-14 08:59 UTC, jongmin4943 commented on src/main/java/persistence/bootstrap/Metamodel.java
> +        DatabaseSyncManager.sync(entityTableBinder, entityAssociationBinder, jdbcTemplate);
현재구조에서는 EntityManagerFactory 가 만들어주신 JPA 스펙에서 가장 상단 객체같으니 거기서 Metamodel 초기화부터 필요한 것들을 초기화 해볼 것 같아요 :)

2024-11-14 09:00 UTC, jongmin4943 commented on src/main/java/persistence/entity/manager/CurrentSessionContext.java
> +    public synchronized EntityManager openSession(EntityManager entityManager) {
어치피 ThreadLocal 이라서 큰 의미가 없지 않을까 생각하는데, 정수님은 어떻게 생각하시나요?

2024-11-14 09:34 UTC, jsyang-dev commented on src/main/java/persistence/entity/manager/CurrentSessionContext.java
> +    public synchronized EntityManager openSession(EntityManager entityManager) {
한번더 래핑하는 느낌이었는데, 불필요할 것 같아서 제거하는 방향으로 수정 진행하였어요