3단계 - Event
next-step/jpa-bootstrap pull request #71
Opened 2024-11-19 12:43 UTC by catsbi

안녕하세요 리뷰어님, PR이 좀 늦어졌습니다. 
Event에 대한 이해도도 좀 부족했고, 온라인강의를 회사일정과 맞물려 보지 못해 힘들어서 좀 시간이 걸린 것 같습니다. 

요구사항 중 ActionQueue(요구사항2)를 제외하고 기능 구현하여 우선 제출합니다 !

2024-11-20 13:37 UTC, jinyoungchoi95 requested changes
안녕하세요 한솔님 😄

몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/impl/DefaultEventListenerGroup.java
> +        listeners.forEach(listener -> listener.onEvent(event));
실제로는 `EventListener`까지 추상화레벨을 올리지 않고, 각 액션에 맞게 `DeleteListener`까지만 추상화되어있어요. 
```java

    @Override
    public void onEvent(Event event) {
        if (event instanceof DeleteEvent) {
            onDelete((DeleteEvent) event);
        }
    }
```
로 잘 구현해주셨지만 엄청나게 많은 Listener들이 있는 가운데 if문을 타는 것 자체가 불필요한 행위가 될 수 도 있어요. 다만 fireEvent를 호출하는 쪽에서 본인들이 수행할 내용들을 담아두고 있습니다.
```java
<U> void fireEventOnEachListener(U event, BiConsumer<T,U> actionOnEvent);


fastSessionServices.eventListenerGroup_DELETE
    .fireEventOnEachListener( event, DeleteEventListener::onDelete );
```
한솔님이 만들어주신 구조는 추상화를 통해 외부에서 fireEvent의 어떤 동작구조를 신경쓸지에 대해서조차도 감출 수 있다가 있을 것 같고, 실제 구현체는 좀 더 실행하는 측에서 명시적인 동작행위를 표현해줄 수 있겠다 정도가 있을 것 같네요.

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/impl/DefaultEventListenerGroup.java
> +    public EventType<T> getEventType() {
사용하는 곳이 없어보이네요 :)

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/impl/DefaultDeleteEventListener.java
> +    }
`DeleteEventListener`를 abstract class로 만들고 해당 클래스에서 `onEvent`를 구현해두면 하위 상세 구현체들에서는 처리할 기본 이벤트인 `DeleteEvent`에 대한 고민을 덜 할 수 있을 것 같아요.

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/impl/DefaultDeleteEventListener.java
> +        EntityManager entityManager = event.entityManager();
event의 `EntityManager`를 가져와서 또 getter로 각 필요 객체를 꺼내는 depth가 늘어나는 구조보다는 event가 각객체를 들고 있으면 바로 가져다 쓸 수 있지 않을까요?

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/impl/DefaultDeleteEventListener.java
> +            EntityPersister<?> entityPersister = entityManager.getEntityPersister(entity.getClass());
이렇게 타입이 자주 사용된다면 `DeleteEvent<T>`를 통해서 각 타입을 더 안정적으로 가져오는 방식이 좋아보이네요.

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/impl/DefaultDeleteEventListener.java
> +        }
get이라는 네이밍은 관습적으로 "반드시 값이 있어 가져올 것을 기대"합니다. null을 반환하는 것이라면 다른 네이밍을 활용하거나 entityEntry가 없는 경우 `PersistenceContext`에서 예외를 던져주는건 어떨까요?

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/EventType.java
> +public class EventType<T> {
구조를 보니 enum이 떠오르네요 :)

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/impl/DefaultEventListenerRegistry.java
> +    private static final Map<EventType<? extends EventListener>, EventListenerGroup<?>> listenerGroups = new HashMap<>();
위에서도 이야기한 내용이지만 잘 추상화되었으나 어떤 listener를 보유중인지는 사실 알아보기 힘들수도 있을 것 같아요. 라이브러리/프레임워크를 만든다는 관점에서는 오히려 추상화하는 것들이 가독성 혹은 유지보수성을 떨어뜨리지는 않는지를 더 우선해야하는 포인트로도 잡을 수 있습니다.

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/persistence/sql/dml/impl/DefaultEntityManager.java
이벤트들이 잘 옮겨져서 가벼워졌네요~

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/persistence/sql/dml/impl/DefaultEntityManager.java
> +        eventListenerGroup.fireEvent(saveOrUpdateEvent);
잘 만들어주신 추상화를 생각해본다면 여기도 get으로 가져오고 수행하기보다는 두 라인을 쓸 필요없이  xx.fireEvent(saveOrUpdateEvent)로 바로 수행할 수 있도록 만들어볼 수도 있겠네요.

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/impl/SaveOrUpdateEvent.java
> +        EntityManager entityManager) implements Event {
`DeleteEvent`와 마찬가지로 제네릭을 고려해볼 수 있을 것 같아요.

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/impl/DefaultSaveOrUpdateEventListener.java
> +        throw new IllegalArgumentException("Event type not supported: " + event.getClass().getName());
여기만 예외가 발생하는 이유가 있을까요?

2024-11-20 13:37 UTC, jinyoungchoi95 commented on src/main/java/event/ActionQueue.java
> +    private final List<EntityUpdateAction> updates = new ArrayList<>();
`Queue`구조를 생각해본다면 `ArrayList`가 아닌 다른 자료구조를 생각해볼 수 있겠네요 :)

2024-11-20 23:55 UTC, catsbi commented on src/main/java/event/impl/DefaultSaveOrUpdateEventListener.java
> +        throw new IllegalArgumentException("Event type not supported: " + event.getClass().getName());
놓친 것 같네요 😓  다른 곳에서도 모두 적절한 구현체가 아닐 경우 예외를 던지고자 하는 의도로 만들었기 때문에 
다른 위치의 리스너들도 예외 발생로직 추가해줬습니다.

2024-11-21 00:02 UTC, catsbi commented on src/main/java/event/impl/DefaultEventListenerGroup.java
> +        listeners.forEach(listener -> listener.onEvent(event));
항상 추상화를하면서 공통화처리를 하려는 편인데, 피드백을통해 무조건적인 추상화가 오히려 독이되는 경우고 있고, 어느정도의 구현체는 의존하는게 코드의 유연성을 더 높힐 수 있다는 생각이 드네요. 추상클래스로 계층을 하나 더 두거나 오버로딩을 좀 더 활용해보겠습니다.

2024-11-21 01:39 UTC, catsbi commented on src/main/java/event/impl/DefaultDeleteEventListener.java
> +    }
추상클래스 계층으로 만들어 onEvent로직에 대해 공통 처리를 하도록 했습니다.

2024-11-21 01:46 UTC, catsbi commented on src/main/java/event/impl/DefaultDeleteEventListener.java
> +        }
저는 오히려 getOrThrow나 getOrDefault와 같은 suffix 네이밍이 해당 함수가 예외 혹은 기본값을 반환한다는 의미를 내포한다고 생각해요. get이나 find, search등은 not-null보단 nullable이지 않을까? 라고 생각합니다. 물론 그렇게 되면 Optional등을 통해 반환하는게 좀 더 nullable하다는 의미를 보여줄 수 있어서 진영님 말대로 PersistenceContext에서 예외를 던지는게 적절할지도 모르겠네요

2024-11-21 01:52 UTC, catsbi commented on src/main/java/event/impl/DefaultEventListenerRegistry.java
> +    private static final Map<EventType<? extends EventListener>, EventListenerGroup<?>> listenerGroups = new HashMap<>();
EventType을 열거형으로 바꾸고 관리되도록 수정했습니다. 
조회시 내부적으로 computeIfAbsente를 이용해 현재 존재하지 않은 경우 기본 ListenerGroup생성을 하도록 해줬습니다.

2024-11-21 04:01 UTC, catsbi commented on src/main/java/event/impl/DefaultDeleteEventListener.java
> +        EntityManager entityManager = event.entityManager();
Delete Event는 가능할 것 같은데, saveOrUpdate나 load같은 이벤트는 자식 객체에 대한 정보들도 포함되다보니 엔티티 매니저가 그대로 사용되는게 더 복잡도도 낮고 가독성도 높을 것 같습니다 🤔

2024-11-22 14:23 UTC, jinyoungchoi95 requested changes
안녕하세요 한솔님 😄

몇가지 코멘트 남겨두었는데 확인부탁드려요 :)

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-11-22 14:23 UTC, jinyoungchoi95 commented on src/main/java/persistence/sql/dml/EntityManager.java
> +    boolean isNew(Object entity);
hibernate의 구현체 구조를 따라갈 필요는 없으나 jpa의 스펙은 따라갈 필요가 있을 것 같아요. `EntityManager`가 `isNew`를 지원하지 않는데 `EntityManger`가 `isNew`를 판별하는게 맞을까요? `EntityManager`는 entity를 관리하는 책임이지 isNew임을 다른 객체들이 사용하게 지원하는 객체는 아니지 않을까요?

2024-11-22 14:23 UTC, jinyoungchoi95 commented on src/main/java/persistence/sql/dml/EntityManager.java
> +    void addUpdateAction(EntityUpdateAction<?> action);
마찬가지로 action을 실행하는 역할은 각 책임을 담당하는 객체가 할 일이지 `EntityManager`의 스펙이라고 보기 어렵습니다. entity를 persist, find 할때 action을 실행하는것이지 본인이 이 스펙을 제공할 필요는 없어보여요. 적절한 객체로 이동해주시면 좋을 것 같아요.

2024-11-22 14:23 UTC, jinyoungchoi95 commented on src/main/java/event/impl/DefaultSaveOrUpdateEventListener.java
> +            entityManager.addInsertionAction(action);
그래서 `EntityManager`에게 실행을 요청하기보다는 `Listener`가 `ActionQueue`를 가지고 있고, 본인이 `actionQueue.addInsertion(action);`를 호출하여야 더 적절해보여요. 혹은 hibernate처럼 `ActionQueue`를 getter로 가져오거나요. 요지는 `EntityManager`는 insertaction이라는 동작 자체를 지원하지 않는 것입니다.

2024-11-22 14:23 UTC, jinyoungchoi95 commented on src/main/java/event/ActionQueue.java
> +    }
이미 queue에 동일한 entity insert action이 있는 경우에 대해서 처리해주어야하지 않을까요?

2024-11-22 14:23 UTC, jinyoungchoi95 commented on src/main/java/event/ActionQueue.java
> +    public void addInsertion(EntityInsertAction<?> action) {
만약 id가 전달되는 entity가 아닌 생성 id의 전략이 identity인 경우에 대한 처리가 필요하지 않을까요?

실제 jpa를 생각해보면 persist에 대해서 "쿼리가 요청하자마자 날아갈때"와 "바로 날아가지 않을때"가 있습니다. 꼭 flush를 하지 않더라도 queue를 비워야하는 상황에 대한 처리가 필요해보여요.

2024-11-23 01:13 UTC, catsbi commented on src/main/java/persistence/sql/dml/EntityManager.java
> +    boolean isNew(Object entity);
행위가 한 군데 이상에서 사용된다는 측면만 고려했던 것 같네요. 다시 private로 고치거나 별도의 컴포넌트로 분리하도록 하겠습니다.

2024-11-23 01:26 UTC, catsbi commented on src/main/java/persistence/sql/dml/EntityManager.java
> +    void addUpdateAction(EntityUpdateAction<?> action);
음 이부분에 대해서는 좀 의문이 듭니다. 
EntityManager 내부적으로 persist를 하면 내부적으로 performSave가 호출되고 그 함수 내부에선 performSaveOrReplicate 함수가 수행되는데 여기선 EventSource에서 getActionQueue로 Queue를 꺼내어 addAction을 해주고 있습니다. 

엔티티 매니저의 역할은 엔티티 관리이긴한데, ActionQueue라는 필드를 캡슐화하여 가지고 있는 객체이기 때문에
Queue를 꺼내어 연산하기보단 적절한 요청을 함수로 호출하여 전달하는게 맞지 않나? 생각이 들어 getActionQueue가 아니라 addXXXXAction으로 함수를 만들어 줬습니다. 

우선 getActionQueue로 큐를 꺼내 작업하는 방식으로 수정했습니다.

2024-11-23 01:47 UTC, catsbi commented on src/main/java/event/impl/DefaultSaveOrUpdateEventListener.java
> +            entityManager.addInsertionAction(action);
위에서 답변한것과 같이 getActionQueue로 큐를 가져오도록 했습니다

2024-11-23 02:33 UTC, catsbi commented on src/main/java/event/ActionQueue.java
> +    }
반복된 insert요청은 중복검사 이후 막도록 분기문을 추가해줬습니다.

2024-11-23 03:48 UTC, catsbi commented on src/main/java/event/ActionQueue.java
> +    public void addInsertion(EntityInsertAction<?> action) {
해당 함수 내에 중복 검사 및 즉시 소비 여부 확인 로직을 추가하였습니다.

2024-11-23 04:14 UTC, catsbi commented
안녕하세요. 리뷰어님 피드백을 통해 이런저런 고민을 많이 하게되어 즐거운 시간인것 같습니다. 
물론 제대로 해결이 안되는것 같다는 생각과 회사 업무가 지금도 몰려오고 있어서 고된부분도 있지만, 인사이트가 있어 좋은 것 같네요!

피드백 주신부분들 토대로 리팩터링 진행하여 봤습니다!

2024-11-24 08:57 UTC, jinyoungchoi95 approved these changes
안녕하세요, 한솔님 😄

미션 수행하시느라 고생 많으셨습니다 👍
JPA 과정을 통해 많은 인사이트를 얻으셨기를 바랍니다 😊

감사합니다! 🙇‍♂️

2024-11-24 08:57 UTC, jinyoungchoi95 commented on src/main/java/event/ActionQueue.java
> +    private final Queue<ChildEntityInsertAction<?, ?>> childEntityInsertions = new ArrayDeque<>();
hibrenate에서는 Entity를 명시하고 있으나 개인적으로는 이미 `ActionQueue` 또한 Entity가 명시되지 않은 것처럼 이미 Entity를 다루는 라이브러리를 만들고 있기 때문에 Action들도 `Entity`가 prefix로 달려있지 않아도 좋을 것 같아요.

2024-11-24 08:57 UTC, jinyoungchoi95 commented on src/main/java/event/ActionQueue.java
> +        }
👍 
실제로는 InsertAction에서 `IdentityInsertAction`이 분리되어 구현되어있는 점만 참고해주시면 좋을 것 같아요.
```java
	public void addAction(EntityIdentityInsertAction action) {
		LOG.tracev( "Adding an EntityIdentityInsertAction for [{0}] object", action.getEntityName() );
		addInsertAction( action );
	}
```

2024-11-24 08:57 UTC, jinyoungchoi95 commented on src/main/java/persistence/sql/dml/EntityManager.java
> +    void addUpdateAction(EntityUpdateAction<?> action);
네 말씀해주신대로 getter로 Queue를 꺼내어 호출하는건 적절하지 않다고 생각합니다 (하이버네이트에선 그렇게 구현하지만요.)

말씀드렸던 내용에서 `EntityManager`가 Action 자체를 실행하는 스펙을 가지지 않는다는걸 염두하고 구현한다면 하이버네이트처럼 getter로 구현하는 방법이 의도했던 첫번째 방법이었는데요. 다른 방법으로는 각 Listener가 register 생성 시에 `ActionQueue`를 주입받는 형태가 있을 것 같아요. 다만 이렇게되면 `Listener`들의 생명주기도 `EntityManager`와 같이 가져가야하는 점이 있습니다.

2024-11-24 08:57 UTC, jinyoungchoi95 commented on src/main/java/event/ActionQueue.java
> +    public void addChildEntityInsertion(ChildEntityInsertAction<?, ?> action) {
`EntityInsertAction` 두개(parent, child)가 추상화가 되었다면 두 queue가 분리되어야하나라는 생각이 들어요. insert의 형태는 동일하고 identity일때의 queue 비움도 parent, child 구분없이 둘다 동작해야하는 것이기 때문에 
```java
private final Queue<AbstractEntityInsertAction<?>> insertions = new ArrayDeque<>();
```
만 받아 addAction(AbstractEntityInsertAction) 였어도 되지 않을까 싶어요.

2024-11-24 08:57 UTC, merged